# Generated by Django 4.0.6 on 2022-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
