# Generated by Django 4.0.6 on 2022-08-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0002_alter_cafe_cafename_alter_place_placename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dang.location'),
        ),
    ]
