# Generated by Django 4.1 on 2022-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0006_alter_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='favorite',
            field=models.BooleanField(null=True),
        ),
    ]
