# Generated by Django 4.1 on 2022-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0007_cafe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
